= Plan API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2

== 계획 생성
=== Request
operation::plans/create[snippets="http-request"]
operation::plans/create[snippets="request-fields"]

=== Response
operation::plans/create[snippets="response-body"]
operation::plans/create[snippets="response-fields"]


== 내 계획 목록 조회
=== Request
operation::plans/find/list[snippets="http-request"]

=== Response
operation::plans/find/list[snippets="response-body"]
operation::plans/find/list[snippets="response-fields"]


== 상세 계획 조회
=== Request
operation::plans/find/detail[snippets="http-request"]

=== Response
operation::plans/find/detail[snippets="response-body"]
operation::plans/find/detail[snippets="response-fields"]


== 계획 이름 변경
=== Request
operation::plans/change/title[snippets="http-request"]
operation::plans/change/title[snippets="path-parameters"]
operation::plans/change/title[snippets="request-fields"]

=== Response
operation::plans/change/title[snippets="response-body"]
operation::plans/change/title[snippets="response-fields"]


== 관광지 검색
=== Request
operation::place/get/list[snippets="http-request"]
operation::place/get/list[snippets="query-parameters"]

=== Response
operation::place/get/list[snippets="response-body"]
operation::place/get/list[snippets="response-fields"]


== 관광지 디테일
=== Request
operation::place/get/detail[snippets="http-request"]
operation::place/get/detail[snippets="path-parameters"]

=== Response
operation::place/get/detail[snippets="response-body"]
operation::place/get/detail[snippets="response-fields"]


== 목적지 추가
=== Request
operation::destinations/add[snippets="http-request"]
operation::destinations/add[snippets="request-fields"]

=== Response
operation::destinations/add[snippets="response-body"]
operation::destinations/add[snippets="response-fields"]


== 목적지 목록 업데이트
=== Request
operation::destinations/update[snippets="http-request"]
operation::destinations/update[snippets="request-fields"]

=== Response
operation::destinations/update[snippets="response-body"]
operation::destinations/update[snippets="response-fields"]


== 목적지 삭제
=== Request
operation::destinations/delete[snippets="http-request"]
operation::destinations/delete[snippets="request-fields"]

=== Response
operation::destinations/delete[snippets="response-body"]
operation::destinations/delete[snippets="response-fields"]