= Plan API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2

== 계획 생성
=== Request
operation::plans/create[snippets="http-request"]
operation::plans/create[snippets="request-fields"]

=== Response
operation::plans/create[snippets="response-body"]
operation::plans/create[snippets="response-fields"]


== 내 계획 목록 조회
=== Request
operation::plans/find/list[snippets="http-request"]

=== Response
operation::plans/find/list[snippets="response-body"]
operation::plans/find/list[snippets="response-fields"]


== 상세 계획 조회
=== Request
operation::plans/find/detail[snippets="http-request"]

=== Response
operation::plans/find/detail[snippets="response-body"]
operation::plans/find/detail[snippets="response-fields"]


== 목적지 목록 업데이트
=== Request
operation::destinations/update[snippets="http-request"]
operation::destinations/update[snippets="request-fields"]

=== Response
operation::destinations/update[snippets="response-body"]
operation::destinations/update[snippets="response-fields"]